### ISSUE TITLE
AVIF?

### ISSUE THREAD

**Issue by berkmh** [HoraceShmorace/Image-Flex#18]
can you add an AVIF handler to serve which ever image (AVIF, webp, etc..)  is smaller in size?

**Comment by HoraceShmorace** [comment]
Sorry, the past year has been busy. I can add support for the AVIF format. However, in order to choose between AVIF and webp based on file size, the service would have to generate both, which would increase computational latency. I **_could_** add the ability to favor AVIF rather than webp via an environment variable or a command line flag. 

If you absolutely need to always use whichever format results in the smaller file size, then I'd suggest creating a simple service that reaches out to your Image Flex instance and requests both file types, compares the sizes of the responses, and  returns the smaller-sized format.

I'll also consider just adding the feature and just making it configurable, but the increase in computation time needed to generate another image would likely negate the savings you'd gain from having the smaller file-sized format on calls to origin.

**Comment by jcam** [comment]
I added AVIF in my fork here (back in 2022) but I found that the time to _generate_ an AVIF was much too long for our user experience so I turned it back off in a later commit.
(there are a few other changes for our use case)
https://github.com/HoraceShmorace/Image-Flex/compare/master...jcam:Image-Flex:master

**Comment by HoraceShmorace** [comment]
Ok, I've done **_a lot_** of testing. The default image format is now AVIF. I haven't seen any additional latency when generating the image. If you encounter any added latency, then you can always warm the cache.
