### ISSUE TITLE
WAFv2 Creation Failed

### ISSUE THREAD

**Issue by 7haveeen** [HoraceShmorace/Image-Flex#9]
Wafv2 only works with the stack deployed in us-east-1 only so trying to use the -- region won't work unless we move back to WAF v1 or WAF Regional.

**Comment by HoraceShmorace** [comment]
There's not much we can do about that but document it and/or switch to v1.

**Comment by HoraceShmorace** [comment]
Hmm. This doesn't fail for me.

**Comment by HoraceShmorace** [comment]
I need to add a condition in the SAM template to use v1 when any region other than us-east-1 is used.

**Comment by 7haveeen** [comment]
Yes thats the solution just that i haven't tried it yet. it should be easy to implement.

**Comment by HoraceShmorace** [comment]
So due to:

1. [The limitations of WAF Classic](https://docs.aws.amazon.com/waf/latest/developerguide/waf-migrating-why-migrate.html) (aka, v1) such as not having support for AWS Managed Rule Sets, and
2. [The limitations of CloudFront](https://docs.aws.amazon.com/waf/latest/developerguide/how-aws-waf-works.html) that require resources associated with a distribution to be created in us-east-1 ...

... the best course of action is to role back multi-region support. This makes disaster recovery implementations more challenging (specifically in which a multi-region, _active-active_ model is required).

**Comment by HoraceShmorace** [comment]
For now, I've removed documentation around setting the region.
